package com.tuoman.ai_task_orchestrator.enums;

public enum IngestionEventType {
    TASK_CREATED,
    TASK_QUEUED,
    TASK_STARTED,
    TEXT_EXTRACTED,
    CHUNKING_STARTED,
    CHUNKING_COMPLETED,
    EMBEDDING_STARTED,
    EMBEDDING_COMPLETED,
    VECTOR_WRITE_STARTED,
    VECTOR_WRITE_COMPLETED,
    TASK_COMPLETED,
    TASK_FAILED,
    TASK_RETRY_REQUESTED,
    TASK_RETRY_QUEUED
}
