package com.tuoman.ai_task_orchestrator.common.error;

public enum ErrorCode {
    TASK_NOT_FOUND,
    INVALID_TASK_STATUS,
    TASK_FINALIZATION_REJECTED,
    DOCUMENT_NOT_FOUND,
    INVALID_REQUEST,
    VALIDATION_ERROR,
    EMBEDDING_PROVIDER_ERROR,
    VECTOR_STORE_ERROR,
    LLM_PROVIDER_ERROR,
    RETRIEVAL_EVALUATION_ERROR,
    INGESTION_TASK_NOT_FOUND,
    INGESTION_RETRY_NOT_ALLOWED,
    INGESTION_MAX_RETRY_EXCEEDED,
    DOCUMENT_DELETED_CANNOT_REINDEX,
    DOCUMENT_SOURCE_TEXT_MISSING,
    DOCUMENT_REINDEX_ALREADY_RUNNING,
    DOCUMENT_REINDEX_FAILED,
    COLLECTION_NOT_FOUND,
    COLLECTION_NAME_REQUIRED,
    COLLECTION_NAME_DUPLICATED,
    DOCUMENT_ALREADY_IN_COLLECTION,
    DOCUMENT_NOT_IN_COLLECTION,
    COLLECTION_ASSIGNMENT_FAILED,
    INTERNAL_ERROR
}
