package sqlite

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"embed"
	"errors"
	"fmt"
	"io/fs"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

//go:embed migrations/*.sql
var migrationFiles embed.FS

type migration struct {
	version  int
	name     string
	checksum string
	sql      string
}

func (s *Store) migrate(ctx context.Context) error {
	migrations, err := readMigrations()
	if err != nil {
		return fmt.Errorf("sqlite: read migrations: %w", err)
	}
	if err := s.withTx(ctx, func(tx *sql.Tx) error {
		_, err := tx.ExecContext(ctx, `
			CREATE TABLE IF NOT EXISTS schema_migrations (
				version INTEGER PRIMARY KEY,
				name TEXT NOT NULL UNIQUE,
				checksum TEXT NOT NULL,
				applied_at TEXT NOT NULL
			) STRICT
		`)
		return err
	}); err != nil {
		return fmt.Errorf("sqlite: create migration ledger: %w", err)
	}

	if err := s.validateMigrationLedger(ctx, migrations); err != nil {
		return err
	}
	for _, item := range migrations {
		if err := s.applyMigration(ctx, item); err != nil {
			return err
		}
	}
	return s.validateMigrationLedger(ctx, migrations)
}

func (s *Store) applyMigration(ctx context.Context, item migration) error {
	return s.withTx(ctx, func(tx *sql.Tx) error {
		var name, checksum string
		err := tx.QueryRowContext(ctx,
			"SELECT name, checksum FROM schema_migrations WHERE version = ?",
			item.version,
		).Scan(&name, &checksum)
		switch {
		case err == nil:
			if name != item.name || checksum != item.checksum {
				return fmt.Errorf("sqlite: migration %03d differs from the applied migration", item.version)
			}
			return nil
		case !errors.Is(err, sql.ErrNoRows):
			return fmt.Errorf("sqlite: inspect migration %03d: %w", item.version, err)
		}

		if _, err := tx.ExecContext(ctx, item.sql); err != nil {
			return fmt.Errorf("sqlite: apply migration %03d_%s: %w", item.version, item.name, err)
		}
		// Migration audit time is deliberately generated by SQLite and may remain
		// text; every product time column uses integer Unix microseconds.
		if _, err := tx.ExecContext(ctx, `
			INSERT INTO schema_migrations(version, name, checksum, applied_at)
			VALUES (?, ?, ?, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
		`, item.version, item.name, item.checksum); err != nil {
			return fmt.Errorf("sqlite: record migration %03d: %w", item.version, err)
		}
		return nil
	})
}

func (s *Store) validateMigrationLedger(ctx context.Context, migrations []migration) error {
	rows, err := s.db.QueryContext(ctx, `
		SELECT version, name, checksum
		FROM schema_migrations
		ORDER BY version
	`)
	if err != nil {
		return fmt.Errorf("sqlite: read migration ledger: %w", err)
	}
	defer rows.Close()
	expected := 1
	for rows.Next() {
		var version int
		var name, checksum string
		if err := rows.Scan(&version, &name, &checksum); err != nil {
			return fmt.Errorf("sqlite: scan migration ledger: %w", err)
		}
		if version > len(migrations) {
			return fmt.Errorf("sqlite: database schema version %d is newer than supported version %d", version, len(migrations))
		}
		if version != expected {
			return fmt.Errorf("sqlite: migration ledger gap: got version %03d, want %03d", version, expected)
		}
		known := migrations[version-1]
		if name != known.name || checksum != known.checksum {
			return fmt.Errorf("sqlite: migration %03d differs from the applied migration", version)
		}
		expected++
	}
	if err := rows.Err(); err != nil {
		return fmt.Errorf("sqlite: iterate migration ledger: %w", err)
	}
	return nil
}

func readMigrations() ([]migration, error) {
	paths, err := fs.Glob(migrationFiles, "migrations/*.sql")
	if err != nil {
		return nil, err
	}
	sort.Strings(paths)
	items := make([]migration, 0, len(paths))
	for index, path := range paths {
		base := filepath.Base(path)
		stem := strings.TrimSuffix(base, filepath.Ext(base))
		versionText, name, ok := strings.Cut(stem, "_")
		if !ok || len(versionText) != 3 || name == "" {
			return nil, fmt.Errorf("invalid migration filename %q", base)
		}
		version, err := strconv.Atoi(versionText)
		if err != nil || version != index+1 {
			return nil, fmt.Errorf("migration %q is out of sequence; want version %03d", base, index+1)
		}
		contents, err := migrationFiles.ReadFile(path)
		if err != nil {
			return nil, err
		}
		digest := sha256.Sum256(contents)
		items = append(items, migration{
			version:  version,
			name:     name,
			checksum: fmt.Sprintf("%x", digest),
			sql:      string(contents),
		})
	}
	if len(items) == 0 {
		return nil, errors.New("no embedded migrations")
	}
	return items, nil
}
