CREATE TABLE task_attempt (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    task_id BIGINT NOT NULL,
    attempt_no INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    worker_id VARCHAR(128) NULL,
    llm_provider VARCHAR(64) NULL,
    llm_model VARCHAR(128) NULL,
    prompt_template_code VARCHAR(128) NULL,
    rendered_prompt TEXT NULL,
    prompt_token_count INT NULL,
    completion_token_count INT NULL,
    total_token_count INT NULL,
    llm_latency_ms BIGINT NULL,
    error_message TEXT NULL,
    started_at DATETIME NOT NULL,
    finished_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_task_attempt_task_id (task_id),
    INDEX idx_task_attempt_task_attempt_no (task_id, attempt_no),
    INDEX idx_task_attempt_status (status),
    UNIQUE KEY uk_task_attempt_task_attempt_no (task_id, attempt_no)
);
