package com.tuoman.ai_task_orchestrator.enums;

public enum AgentTaskEventType {
    TASK_CREATED,
    TASK_QUEUED,
    TASK_STARTED,
    RETRIEVAL_STARTED,
    RETRIEVAL_COMPLETED,
    LLM_STARTED,
    LLM_COMPLETED,
    TASK_COMPLETED,
    TASK_FAILED,
    STEP_PLAN_CREATED,
    TOOL_EXECUTION_STARTED,
    TOOL_EXECUTION_COMPLETED,
    TOOL_EXECUTION_FAILED,
    FINAL_REPORT_STARTED,
    FINAL_REPORT_COMPLETED,
    FINAL_REPORT_FAILED
}
