package com.tuoman.ai_task_orchestrator.enums;

public enum VectorAuditIssueType {
    DUPLICATE_VECTOR,
    ORPHAN_VECTOR,
    MISSING_VECTOR,
    CROSS_COLLECTION_VECTOR_LEAK,
    WRONG_GENERATION_VECTOR,
    MODEL_DIMENSION_MISMATCH,
    TRASHED_VECTOR_VISIBLE,
    PURGED_VECTOR_RESIDUE,
    PAYLOAD_METADATA_MISMATCH
}
